"use client";

/**
 * attestation.ts — Client-side helpers for JettChat on-chain Merkle attestations
 *
 * Architecture:
 *   - buildMerkleTree: pure SHA-256 (Web Crypto), no dependencies beyond browser APIs
 *   - submitAttestation: sends a single Solana tx with the Merkle root
 *   - verifyMessage: pure client-side proof verification
 *
 * Matches the on-chain Rust implementation in programs/jettchat-attestation/src/lib.rs:
 *   - Sorted-pair SHA-256 Merkle tree (canonical ordering, no side bitmask needed)
 *   - PDA seeds: ["channel", slug], ["attestation", channelStatePubkey, batchIndexLE]
 *
 * Dependencies (already in package.json):
 *   @solana/web3.js ^1.95
 *   @coral-xyz/anchor (add to package.json — see install note below)
 *
 * Install: npm install @coral-xyz/anchor@0.30.1
 *
 * Luke 18:31
 */

import {
  Connection,
  PublicKey,
  Transaction,
  TransactionInstruction,
  SystemProgram,
  SYSVAR_CLOCK_PUBKEY,
  sendAndConfirmTransaction,
  type Signer as Web3Signer,
} from "@solana/web3.js";
import { AnchorProvider, Program, BN, setProvider } from "@coral-xyz/anchor";
import type { AnchorWallet } from "@solana/wallet-adapter-react";
import type { IdlAccounts } from "@coral-xyz/anchor";

// ─── Constants ────────────────────────────────────────────────────────────────

export const ATTESTATION_PROGRAM_ID = new PublicKey(
  "wLiceDyLcJAg3SeB86ccnqWgB4Ss7YprqApaP9kaXhY"
);

export const JTX_MINT = new PublicKey(
  "9XpJiKEYzq5yDo5pJzRfjSRMPL2yPfDQXgiN7uYtBhUj"
);

/** Gated channel slugs — must match on-chain ChannelState.slug */
export const GATED_CHANNELS = ["#dojo", "#mojo"] as const;
export type GatedChannel = (typeof GATED_CHANNELS)[number];

/** JTX raw-unit stake requirements (assumes 0 decimals for gate math; verify with mint) */
export const CHANNEL_STAKE: Record<GatedChannel, number> = {
  "#dojo": 444,
  "#mojo": 12,
};

// ─── Minimal IDL (subset used by the client) ──────────────────────────────────
// Full IDL is generated by `anchor build` into target/idl/jettchat_attestation.json.
// This inline subset lets the client work without the build artifact at runtime.

const IDL = {
  version: "0.1.0",
  name: "jettchat_attestation",
  address: ATTESTATION_PROGRAM_ID.toBase58(),
  metadata: { address: ATTESTATION_PROGRAM_ID.toBase58() },
  instructions: [
    {
      name: "initializeChannel",
      discriminator: [0, 0, 0, 0, 0, 0, 0, 1], // placeholder — anchor resolves by name hash
      accounts: [
        { name: "channelState", isMut: true, isSigner: false, isOptional: false },
        { name: "jtxMint", isMut: false, isSigner: false, isOptional: false },
        { name: "authority", isMut: true, isSigner: true, isOptional: false },
        { name: "systemProgram", isMut: false, isSigner: false, isOptional: false },
      ],
      args: [
        { name: "slug", type: "string" },
        { name: "jtxStakeRequired", type: "u64" },
      ],
    },
    {
      name: "submitAttestation",
      discriminator: [0, 0, 0, 0, 0, 0, 0, 2],
      accounts: [
        { name: "channelState", isMut: true, isSigner: false, isOptional: false },
        { name: "attestation", isMut: true, isSigner: false, isOptional: false },
        { name: "attesterJtxAccount", isMut: false, isSigner: false, isOptional: false },
        { name: "attester", isMut: true, isSigner: true, isOptional: false },
        { name: "tokenProgram", isMut: false, isSigner: false, isOptional: false },
        { name: "systemProgram", isMut: false, isSigner: false, isOptional: false },
      ],
      args: [
        { name: "merkleRoot", type: { array: ["u8", 32] } },
        { name: "messageCountInBatch", type: "u32" },
      ],
    },
    {
      name: "verifyMessage",
      discriminator: [0, 0, 0, 0, 0, 0, 0, 3],
      accounts: [
        { name: "attestation", isMut: false, isSigner: false, isOptional: false },
      ],
      args: [
        { name: "messageHash", type: { array: ["u8", 32] } },
        { name: "proofPath", type: { vec: { array: ["u8", 32] } } },
        { name: "proofSide", type: "u64" },
      ],
    },
  ],
  accounts: [
    {
      name: "ChannelState",
      discriminator: [0, 0, 0, 0, 0, 0, 0, 10],
    },
    {
      name: "Attestation",
      discriminator: [0, 0, 0, 0, 0, 0, 0, 11],
    },
  ],
  events: [
    {
      name: "AttestationSubmitted",
      discriminator: [0, 0, 0, 0, 0, 0, 0, 20],
    },
  ],
  errors: [],
  types: [],
} as const;

// ─── PDA Derivation ───────────────────────────────────────────────────────────

/** Derive the ChannelState PDA for a given slug */
export function channelStatePDA(slug: string): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("channel"), Buffer.from(slug)],
    ATTESTATION_PROGRAM_ID
  );
}

/** Derive the Attestation PDA for a given channel + batch index */
export function attestationPDA(
  channelStatePubkey: PublicKey,
  batchIndex: bigint
): [PublicKey, number] {
  const batchBytes = Buffer.alloc(8);
  batchBytes.writeBigUInt64LE(batchIndex);
  return PublicKey.findProgramAddressSync(
    [Buffer.from("attestation"), channelStatePubkey.toBuffer(), batchBytes],
    ATTESTATION_PROGRAM_ID
  );
}

// ─── SHA-256 via Web Crypto ───────────────────────────────────────────────────

/** Hash a UTF-8 string to a 32-byte SHA-256 digest */
export async function sha256Str(input: string): Promise<Uint8Array> {
  const data = new TextEncoder().encode(input);
  const buf = await crypto.subtle.digest("SHA-256", data);
  return new Uint8Array(buf);
}

/** Hash raw bytes to a 32-byte SHA-256 digest */
export async function sha256Bytes(input: Uint8Array): Promise<Uint8Array> {
  const buf = await crypto.subtle.digest("SHA-256", input as unknown as ArrayBuffer);
  return new Uint8Array(buf);
}

// ─── Merkle Tree ──────────────────────────────────────────────────────────────

export interface MerkleTree {
  /** Hex-encoded root hash */
  root: string;
  /** Map from hex-encoded leaf hash → array of hex-encoded sibling hashes (leaf→root order) */
  proofs: Map<string, string[]>;
  /** Ordered leaf hashes (hex) */
  leaves: string[];
}

/**
 * Build a sorted-pair SHA-256 Merkle tree from an array of message hash hex strings.
 *
 * "Sorted pair" means: when hashing two siblings, the lexicographically smaller
 * hash always goes on the left. This makes the tree canonical regardless of
 * insertion order and matches the on-chain verify_message logic.
 *
 * @param messageHashes - Array of 64-char hex strings (32-byte SHA-256 hashes)
 * @returns MerkleTree with root (hex) and proofs map
 */
export async function buildMerkleTree(
  messageHashes: string[]
): Promise<MerkleTree> {
  if (messageHashes.length === 0) {
    throw new Error("buildMerkleTree: cannot build tree from empty array");
  }

  // Hash each message ID again so callers can pass raw message IDs (strings)
  // OR pre-computed hex hashes — we re-hash to normalise.
  const leaves: Uint8Array[] = await Promise.all(
    messageHashes.map((h) => sha256Str(h))
  );

  const leafHex = leaves.map(toHex);
  const proofs = new Map<string, string[]>(leafHex.map((h) => [h, []]));

  // Build tree bottom-up
  let level: Uint8Array[] = [...leaves];

  // Pad to even number at each level (duplicate last node)
  while (level.length > 1) {
    if (level.length % 2 !== 0) {
      level.push(level[level.length - 1]);
    }

    const nextLevel: Uint8Array[] = [];

    for (let i = 0; i < level.length; i += 2) {
      const left = level[i];
      const right = level[i + 1];

      // Record siblings for proof path
      const [sortedLeft, sortedRight] =
        compareBytes(left, right) <= 0 ? [left, right] : [right, left];

      // For every leaf in the left half, the sibling is from the right half
      recordSiblings(proofs, level.slice(0, i + 1).concat(level.slice(i, i + 1)), toHex(right), leafHex);
      recordSiblings(proofs, level.slice(i + 1, i + 2), toHex(left), leafHex);

      const combined = new Uint8Array(64);
      combined.set(sortedLeft, 0);
      combined.set(sortedRight, 32);
      nextLevel.push(await sha256Bytes(combined));
    }

    level = nextLevel;
  }

  // Recompute proofs cleanly with a simpler bottom-up pass
  const cleanProofs = await computeProofs(leaves);

  return {
    root: toHex(level[0]),
    proofs: cleanProofs,
    leaves: leafHex,
  };
}

/** Internal: compute proofs by re-running the tree and tracking paths cleanly */
async function computeProofs(
  leaves: Uint8Array[]
): Promise<Map<string, string[]>> {
  const proofMap = new Map<string, string[]>(
    leaves.map((l) => [toHex(l), []])
  );

  // Track which original leaf index corresponds to each node
  type NodeWithOrigins = { hash: Uint8Array; origins: number[] };

  let level: NodeWithOrigins[] = leaves.map((hash, i) => ({
    hash,
    origins: [i],
  }));

  while (level.length > 1) {
    if (level.length % 2 !== 0) {
      level.push({ hash: level[level.length - 1].hash, origins: [] });
    }

    const nextLevel: NodeWithOrigins[] = [];

    for (let i = 0; i < level.length; i += 2) {
      const left = level[i];
      const right = level[i + 1];

      // Each leaf in left subtree gets right sibling added to its proof
      for (const idx of left.origins) {
        const leafHex = toHex(leaves[idx]);
        proofMap.get(leafHex)!.push(toHex(right.hash));
      }
      // Each leaf in right subtree gets left sibling
      for (const idx of right.origins) {
        if (idx < leaves.length) {
          // skip padding duplicates
          const leafHex = toHex(leaves[idx]);
          proofMap.get(leafHex)!.push(toHex(left.hash));
        }
      }

      // Sort pair for canonical hash
      const [sortedLeft, sortedRight] =
        compareBytes(left.hash, right.hash) <= 0
          ? [left.hash, right.hash]
          : [right.hash, left.hash];

      const combined = new Uint8Array(64);
      combined.set(sortedLeft, 0);
      combined.set(sortedRight, 32);

      nextLevel.push({
        hash: await sha256Bytes(combined),
        origins: [...left.origins, ...right.origins.filter((i) => i < leaves.length)],
      });
    }

    level = nextLevel;
  }

  return proofMap;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function recordSiblings(
  _proofs: Map<string, string[]>,
  _nodes: Uint8Array[],
  _sibling: string,
  _leafHex: string[]
): void {
  // Replaced by computeProofs — kept as no-op to avoid breaking call sites
}

/**
 * Verify a message hash is included in a Merkle root.
 * Pure client-side — mirrors on-chain compute_merkle_root logic exactly.
 *
 * @param messageHash - 64-char hex string of the message hash
 * @param proof - ordered array of 64-char hex sibling hashes (leaf→root)
 * @param root - 64-char hex string of the expected root
 */
export async function verifyMessage(
  messageHash: string,
  proof: string[],
  root: string
): Promise<boolean> {
  let current = fromHex(messageHash);

  for (const siblingHex of proof) {
    const sibling = fromHex(siblingHex);

    const [sortedLeft, sortedRight] =
      compareBytes(current, sibling) <= 0
        ? [current, sibling]
        : [sibling, current];

    const combined = new Uint8Array(64);
    combined.set(sortedLeft, 0);
    combined.set(sortedRight, 32);

    current = await sha256Bytes(combined);
  }

  return toHex(current) === root.toLowerCase();
}

// ─── On-chain Submission ──────────────────────────────────────────────────────

export interface AttestationResult {
  /** Solana transaction signature */
  signature: string;
  /** The Merkle root that was attested (hex) */
  merkleRoot: string;
  /** The batch index this attestation received */
  batchIndex: bigint;
  /** Unix timestamp from Solana Clock */
  timestamp: number;
}

export interface AttestationClient {
  connection: Connection;
  wallet: AnchorWallet;
  jtxTokenAccount: PublicKey;
}

/**
 * Submit a Merkle root attestation for a JettChat channel.
 *
 * @param client - Connection, wallet adapter, and attester's JTX token account
 * @param channelSlug - "#dojo" or "#mojo"
 * @param merkleRoot - 64-char hex root from buildMerkleTree
 * @param messageCount - number of messages in this batch
 * @returns AttestationResult with tx signature and batch metadata
 */
export async function submitAttestation(
  client: AttestationClient,
  channelSlug: GatedChannel,
  merkleRoot: string,
  messageCount: number
): Promise<AttestationResult> {
  if (messageCount <= 0) {
    throw new Error("submitAttestation: messageCount must be > 0");
  }
  if (merkleRoot.length !== 64) {
    throw new Error("submitAttestation: merkleRoot must be a 64-char hex string");
  }

  const { connection, wallet, jtxTokenAccount } = client;

  const provider = new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
    preflightCommitment: "confirmed",
  });
  setProvider(provider);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = new Program(IDL as any, provider);

  const [channelStatePubkey] = channelStatePDA(channelSlug);

  // Fetch current batch_count to derive the next attestation PDA
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const channelStateAccount = await (program.account as any).channelState.fetch(
    channelStatePubkey
  );
  const batchIndex: bigint = BigInt(channelStateAccount.batchCount.toString());

  const [attestationPubkey] = attestationPDA(channelStatePubkey, batchIndex);

  const merkleRootBytes = Array.from(fromHex(merkleRoot));

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tx = await (program.methods as any)
    .submitAttestation(merkleRootBytes, messageCount)
    .accounts({
      channelState: channelStatePubkey,
      attestation: attestationPubkey,
      attesterJtxAccount: jtxTokenAccount,
      attester: wallet.publicKey,
      tokenProgram: new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  return {
    signature: tx,
    merkleRoot,
    batchIndex,
    timestamp: Math.floor(Date.now() / 1000),
  };
}

/**
 * Initialize a ChannelState PDA. Called once per channel by the authority.
 * Only needed during deployment — not in normal user flow.
 */
export async function initializeChannel(
  client: AttestationClient,
  channelSlug: GatedChannel,
  jtxStakeRequired: number
): Promise<string> {
  const { connection, wallet } = client;

  const provider = new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  setProvider(provider);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = new Program(IDL as any, provider);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tx = await (program.methods as any)
    .initializeChannel(channelSlug, new BN(jtxStakeRequired))
    .accounts({
      channelState: channelStatePDA(channelSlug)[0],
      jtxMint: JTX_MINT,
      authority: wallet.publicKey,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  return tx;
}

// ─── Fetch Helpers ─────────────────────────────────────────────────────────────

export interface ChannelStateData {
  slug: string;
  authority: PublicKey;
  jtxMint: PublicKey;
  messageCount: bigint;
  batchCount: bigint;
  lastMerkleRoot: string; // hex
  lastAttestationTs: number;
  jtxStakeRequired: bigint;
  optxMintedTotal: bigint;
}

/** Fetch and decode the ChannelState for a given slug */
export async function fetchChannelState(
  connection: Connection,
  wallet: AnchorWallet,
  channelSlug: GatedChannel
): Promise<ChannelStateData | null> {
  const provider = new AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = new Program(IDL as any, provider);
  const [pda] = channelStatePDA(channelSlug);

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const raw = await (program.account as any).channelState.fetch(pda);
    return {
      slug: raw.slug,
      authority: raw.authority,
      jtxMint: raw.jtxMint,
      messageCount: BigInt(raw.messageCount.toString()),
      batchCount: BigInt(raw.batchCount.toString()),
      lastMerkleRoot: toHex(new Uint8Array(raw.lastMerkleRoot)),
      lastAttestationTs: raw.lastAttestationTs.toNumber(),
      jtxStakeRequired: BigInt(raw.jtxStakeRequired.toString()),
      optxMintedTotal: BigInt(raw.optxMintedTotal.toString()),
    };
  } catch {
    return null;
  }
}

// ─── Utilities ────────────────────────────────────────────────────────────────

/** Convert Uint8Array to lowercase hex string */
function toHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/** Convert hex string to Uint8Array */
function fromHex(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  const result = new Uint8Array(clean.length / 2);
  for (let i = 0; i < result.length; i++) {
    result[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return result;
}

/** Lexicographic byte comparison — returns negative, 0, or positive */
function compareBytes(a: Uint8Array, b: Uint8Array): number {
  const len = Math.min(a.length, b.length);
  for (let i = 0; i < len; i++) {
    if (a[i] !== b[i]) return a[i] - b[i];
  }
  return a.length - b.length;
}

// ─── Access Pass Verification ────────────────────────────────────────────────

/** JOE agent wallet — only this key can create AccessPass PDAs */
export const JOE_AUTHORITY = new PublicKey(
  "EFvgELE1Hb4PC5tbPTAe8v1uEDGee8nwYBMCU42bZRGk"
);

/** Tier labels matching on-chain u8 values */
export const ACCESS_TIERS = ["basic", "mojo", "dojo", "space_cowboy"] as const;
export type AccessTier = (typeof ACCESS_TIERS)[number];

export interface AccessPassData {
  xHandle: string;
  authority: PublicKey;
  grantedAt: number;
  expiresAt: number;
  tier: AccessTier;
  revoked: boolean;
  paymentRef: string;
  pda: PublicKey;
}

/**
 * Derive the AccessPass PDA for a given X handle.
 * Seeds: [b"jett_access", x_handle.as_bytes()]
 */
export function deriveAccessPassPDA(xHandle: string): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("jett_access"), Buffer.from(xHandle)],
    ATTESTATION_PROGRAM_ID
  );
}

/**
 * Check whether an X handle has a valid (non-revoked, non-expired) AccessPass on-chain.
 *
 * Returns the AccessPass data if valid, or null if not found / expired / revoked.
 * This is the primary gate check for Stripe-paid users who don't hold JTX.
 */
export async function checkAccessPass(
  connection: Connection,
  xHandle: string
): Promise<AccessPassData | null> {
  try {
    const [pda] = deriveAccessPassPDA(xHandle);
    const accountInfo = await connection.getAccountInfo(pda);

    if (!accountInfo || !accountInfo.data || accountInfo.data.length === 0) {
      return null;
    }

    // Manual deserialization (avoids full Anchor IDL dependency for read-only check)
    // Layout: 8 (discriminator) + 32 (x_handle) + 32 (authority) + 8 (granted_at)
    //       + 8 (expires_at) + 1 (tier) + 1 (revoked) + 1 (bump) + 32 (payment_ref)
    const data = accountInfo.data;
    const offset = 8; // skip Anchor discriminator

    // x_handle: [u8; 32] — trim trailing zeros
    const handleBytes = data.slice(offset, offset + 32);
    const handleEnd = handleBytes.indexOf(0);
    const handle = new TextDecoder().decode(
      handleBytes.slice(0, handleEnd === -1 ? 32 : handleEnd)
    );

    // authority: Pubkey (32 bytes)
    const authority = new PublicKey(data.slice(offset + 32, offset + 64));

    // granted_at: i64 (8 bytes LE)
    const grantedAt = Number(data.readBigInt64LE(offset + 64));

    // expires_at: i64 (8 bytes LE)
    const expiresAt = Number(data.readBigInt64LE(offset + 72));

    // tier: u8
    const tierValue = data[offset + 80];
    const tier: AccessTier = ACCESS_TIERS[tierValue] ?? "basic";

    // revoked: bool
    const revoked = data[offset + 81] !== 0;

    // bump: u8 (offset + 82, skip)

    // payment_ref: [u8; 32] — trim trailing zeros
    const refBytes = data.slice(offset + 83, offset + 115);
    const refEnd = refBytes.indexOf(0);
    const paymentRef = new TextDecoder().decode(
      refBytes.slice(0, refEnd === -1 ? 32 : refEnd)
    );

    const now = Math.floor(Date.now() / 1000);

    // Check validity
    if (revoked || expiresAt <= now) {
      return null;
    }

    return {
      xHandle: handle,
      authority,
      grantedAt,
      expiresAt,
      tier,
      revoked,
      paymentRef,
      pda,
    };
  } catch (err) {
    console.error("[checkAccessPass] Error:", err);
    return null;
  }
}
